# Generated by Django 5.0.3 on 2024-03-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'managed': False, 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={'managed': False, 'verbose_name_plural': 'Disponibilidad'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': False, 'verbose_name_plural': 'Inventario'},
        ),
        migrations.AlterModelOptions(
            name='pqrs',
            options={'managed': False, 'verbose_name_plural': 'PQRS'},
        ),
    ]
